### ISSUE TITLE
안녕하세요 백엔드 여러분

### ISSUE THREAD

**Issue by raejoonee** [YAPP-19th/Web-Team-1-Backend#58]
불철주야 고생이 많으십니다 🙇 

### @ayoung0073
* [x] 퀘스트 등록한 뒤 그 퀘스트 조회해 보면 `tagList`에 있는 값이 전부 null로 보여요 ㅠㅠ
---
### @ayoung0073가 직접 추가
* [x] 퀘스트 리스트 페이징 처리
* [x] 퀘스트 totalCount 데이터 추가
* [x] 퀘스트 완료 기능: 포인트 수정
* [x] 퀘스트 포기(참여한거 취소)하는 API가 필요해요
* [ ] 
### @s2moon98 
* [x] `/api/quests/{questId}/reviews` 요청했을 때 `totalReviewCount`와 `reviewList`의 length랑 달라요
  * 다른 데이터 여러 개 확인해봤는데 `reviewList`에 데이터가 있는 퀘스트가 하나도 없어요 😨
* [x] `/api/quests/{questId}/review`에 PATCH 요청을 보냈을 때 ~~404 Entity Not Found Error~~ _는 해결됐는데 이제_ 400 Error Cannot Create Quest Review ❌ 가 발생합니다.
* [x] 퀘스트 페이징 처리 해주신 #57 처럼 **한 줄 후기**도 이렇게 만들어주실 수 있나요?
  * https://github.com/YAPP-19th/Web-Team-1-Backend/pull/62 에서 merge될 예정이네요 확인했습니다 감사해요 🙇
* [x]  리뷰(한줄평) 작성이 400 Error를 반환하면서 정상적으로 동작이 안 되는 중이에요 😭
* [x] `/api/roadmaps/${roadmapId}` 요청했을 때 `roadmapId`가 1인 경우를 제외하고는 모두 404 Entity Not Found Error ❌ 가 발생합니다.
## 질문사항
* [x] 얘는 POST로 요청할까요 PATCH로 요청할까요?
![image](https://user-images.githubusercontent.com/59731373/148665592-1bc1d92a-06bd-4df9-801e-38486267a9a2.png)

**Comment by ayoung0073** [comment]
한 줄 추가 페이징 처리는 @s2moon98 님이 맡으셔서 수정해놨어요!!
퀘스트 한 줄 추가는 `PATCH` 입니당!

기타 해결해야 할 이슈들 제가 직접 추가해놨어요 계속 수정할게유!

**Comment by raejoonee** [comment]
혹시 이 부분 요청드렸었는데 지금 개발 중이신가요? 개발 시작 안 하셨으면 안 해주셔도 될 것 같아서요! FE 단에서 로직을 바꾸겠습니다. 만약에 이미 개발이 끝난 부분이라면 말씀 주세요 😉 
* **`/api/quests/positions/count` 요청했을 때 항상 응답 데이터 배열의 0번째 index에 아래 값을 넣어서 보내주세요 🙏** 
```json
{
  "position" : "퀘스트 전체",
  "questCount" : {모든 퀘스트 개수},
}
```
  * API
![image](https://user-images.githubusercontent.com/59731373/148665609-3cd80d40-588b-4054-a452-0232958f0dde.png)
  * Expected Response Data Example
```json
[{
  "position" : "퀘스트 전체",
  "questCount" : {모든 퀘스트 개수(이 예제에서는 10)},
}, {
  "position" : "BACKEND",
  "questCount" : 3,
}, {
  "position" : "FRONTEND",
  "questCount" : 7,
}]
```

**Comment by raejoonee** [comment]
전부 해결되어 close
