### ISSUE TITLE
API에 대한 질문 사항

### ISSUE THREAD

**Issue by raejoonee** [YAPP-19th/Web-Team-1-Backend#64]
* [x] `/api/quests/1/complete`로 PATCH 요청을 보내면 아래 응답이 반환됩니다. 퀘스트 완료 요청을 보내는데 퀘스트가 완료되지 않았다고 응답이 오는 이유가 뭘까요 😢 혹시 subquest를 완료하지 않아서인가 하고 subquest도 체크해봤는데 모든 subquest를 완료한 상황입니다! (Request header에는 제공받은 authentication key를 담아 보내고 있습니다)
```
{
  "status": 400,
  "code": "Q003",
  "message": "Not Completed Quest"
}
```
* [x] `/api/quests/1/review`로 PATCH 요청을 보내면 아래 응답이 오는데 혹시 이유가 퀘스트 완료 상태가 아니어서인가요? 🤔 
```
{
  "status": 400,
  "code": "Q003",
  "message": "Not Completed Quest"
}
```
* [x] `/api/roadmaps?size=12`로 GET 요청을 보내면 분명 `id`가 3, 4, 5, ..., 9인 로드맵이 존재하는 것 같은데, 실제로 `/api/roadmaps/${roadmapId}`로 `roadmapId`가 3, 4, 5, ..., 9인 요청을 보내면 404 Entity Not Found Error ❌ 가 뜨네요.. 이유가 뭘까요?
```
{
"status": 404,
"code": "C005",
"message": "Entity Not Found"
}
```

바쁠텐데 자꾸 #58 에 이슈 쌓고 질문까지 하고 미안해요.. 🙇 화이팅... 🙌

**Comment by ayoung0073** [comment]
헉 답이 늦었어요 저녁에 확인하고 말씀드릴게요~!

**Comment by s2moon98** [comment]
1. 서브 퀘스트가 모두 완료되지 않은 상태로 퀘스트 완료를 요청할 경우 해당 에러가 발생합니다.
오류 메세지는 추후에 바꾸겠습니다

2. 완료하지 않은 퀘스트에 리뷰를 작성하려고 할 경우 해당 에러가 발생합니다.
마찬가지로 오류 메세지 수정하도록 할게요!

3. 로드맵 상세 조회에서 Entity Not Found 에러 나는 부분은 수정해서 배포 완료했습니다! 확인 부탁드려요!
@raejoonee

**Comment by raejoonee** [comment]
@s2moon98 
1. 서브퀘스트가 모두 완료되었는데도 에러가 발생합니다 😢 
    * `/api/quests/1/subquests`에서 `subQuestProgressList` 모든 내부 객체의 `isCompleted`가 `true`인 것을 확인했습니다.
2. 감사합니다 😊 
3. 확인했는데 잘 나옵니다! 감사합니다 😊

**Comment by s2moon98** [comment]
허걱 지금 찾아보니 subQuestProgressList 를 보여주는 api가 잘못되어 있었어요ㅜㅜ 수정하고 알려드리겠습니닷

**Comment by s2moon98** [comment]
@raejoonee 
subQuestProgressList 보여주는 api 수정해서 배포 완료했어요!! 확인 부탁드려요~

**Comment by raejoonee** [comment]
전부 해결되어 close
